apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: roshanx/store-app-checkout:latest
        ports:
        - containerPort: 8080
        env:
        # ✅ Existing environment variables
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: NODE_ENV
          value: "production"

        # ✅ ADD THESE MISSING ENVIRONMENT VARIABLES:
        - name: RETAIL_CHECKOUT_PERSISTENCE_PROVIDER
          value: "redis"
        - name: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
          value: "redis://redis:6379"
        - name: RETAIL_CHECKOUT_PERSISTENCE_REDIS_READER_URL
          value: "redis://redis:6379"
        - name: RETAIL_CHECKOUT_ENDPOINTS_ORDERS
          value: "http://orders:8083"
        - name: RETAIL_CHECKOUT_SHIPPING_NAME_PREFIX
          value: "Retail Store"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: store-app
spec:
  selector:
    app: checkout
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8080
